Byeong-Chan/SeaUCode-Back

package-lock.json

package-lock.json 문제 역시 해결하였습니다.

보안 문제 해결 2

---

models/model.js

modify model [model.js]

---

app.js
models/model.js
public/stylesheets/style.css
routes/api/class_handling/class.js
routes/api/loggedIn.js
routes/api/login.js
routes/api/user_handling/register.js
routes/middleware/auth.js

모델 수정 및, send 함수를 json 함수로 모두 고쳤습니다.
추가로 register에 nickname 이 없던걸 추가했습니다.

Class Router 추가

---

models/model.js
routes/api/class_handling/class.js

모델 수정
classroom 
user_list: [String]
user
solved_problems: [Number]

모델을 수정하고 모델을 수정함으로서 발생하는 버그 해결

---

app.js
routes/api/user_handling/user.js

register하고 app.js 수정

---

add.js
delete.js

add,delete api

---

routes/api/class_handling/class.js
routes/api/problem_handling/problems.js

14-2/16-2/27-2/28-2

---

routes/api/class_handling/class.js
routes/api/problem_handling/problems.js

class(14-2,16-2)하고 problem(20-2,27-2,28-2)

---

routes/api/class_handling/class.js

response에 nickname하고 name을 하나씩만 보냈었어서 수정합니다.

13-1 modify [class.js]

---

routes/api/class_handling/class.js

17-2 updated

---

routes/api/problem_handling/problems.js

22-2 updated

---

routes/api/assignment_handling/assignment.js
routes/api/class_handling/class.js

json message

---

routes/api/assignment_handling/assignment.js
routes/api/class_handling/class.js
routes/api/problem_handling/problems.js

15-6수정 29-2 추가 [assignment.js], 14-2,16-2 수정 그리고 14-2 front에서 Student.jsx에서 addStudent할때 nickname뿐만 아니라 반_id도 같이 넘겨줘야합니다. deleteStudent 구현안되어있음

15-6수정 29-2 추가 [assignment.js]

---

routes/api/class_handling/class.js
routes/api/problem_handling/problems.js

14-2,16-2 이름 student.jsx보고 변경하였고 27-2와 28-2를 problem.js에서 class.js로 이동

getAssignmentList 경로 변경

---

models/model.js
routes/api/assignment_handling/assignment.js
routes/api/judge_handling/pending.js

쿼리의 간소화를 위해서 모델을 급히 수정했으며, 15-6을 전면적으로 개편했습니다.

15-6 개편 및, 모델 수정

---

models/model.js
routes/api/assignment_handling/assignment.js
routes/api/judge_handling/pending.js

쿼리의 간소화를 위해서 모델을 급히 수정했으며, 15-6을 전면적으로 개편했습니다.

15-6 개편 및, 모델수정

---

routes/api/class_handling/class.js

이 두 내용을 getClassInfo에 추후에 포함시킬 것입니다.

8-3 8-4 [class.js]

---

routes/api/class_handling/class.js

38-2 searchClass/TeacherNickname , searchClass/Classname

38-2 searchClass

---

routes/api/class_handling/class.js

Leejonghyeon

---

routes/api/problem_handling/problems.js

recommendationtion boj
